### ISSUE TITLE
求个示例看看

### ISSUE THREAD

**Issue by jackadam1981** [pycasbin/flask-authz#1]
求个示例看看

**Comment by jackadam1981** [comment]
不完整的示例，根本没看明白怎么做。

**Comment by allendu91** [comment]
authz_model.conf这个文件的实例呢。

**Comment by techoner** [comment]
Refer to examples in other language versions.

**Comment by jackadam1981** [comment]
user = request.remote_user  # subject

who to set  request.remote_user and read at  middleware.py.

**Comment by jackadam1981** [comment]
> 
> 
> authz_model.conf这个文件的实例呢。

在casbin的源码里面

**Comment by hsluoyz** [comment]
It's authentication's business to set a logged in username.
