### ISSUE TITLE
Bearer authorization token is not yet available

### ISSUE THREAD

**Issue by msdcanderson** [pycasbin/flask-authz#10]
In utils/auth_decoder.py the bearer type authorization is not yet available:

```py
 if type == "Basic":
        """Basic format <user>:<password> return only the user"""
        return b64decode(token).decode().split(":")[0]
    elif type == "Bearer":
        raise UnSupportedAuthType("Bearer is not implemented yet")
```

Are there any plans to add this?

I am looking at including this in a project.  Here is some code I started playing with to add to auth_decoder.py.

```py
import os
import jwt

    if type == "Basic":
        """Basic format <user>:<password> return only the user"""
        return b64decode(token).decode().split(":")[0]
    elif type == "Bearer":
        """Bearer format, returns the identity"""
        decoded_jwt = jwt.decode(token, os.environ["JWT_SECRET_KEY"], algorithms=['HS256'])
        return str(decoded_jwt["identity"])
```

Happy to put together a pull request

**Comment by hsluoyz** [comment]
@msdcanderson glad to see the PR coming!

@dfresh613 @jessecooper can you help review the PR?

**Comment by hsluoyz** [comment]
@techoner @xhy-5000 please also take a look about the progress!

**Comment by jessecooper** [comment]
@msdcanderson This is something I was definitely looking to the community to implement as I use a different process for handling Bearer tokens so I would love to see a PR for this. The code looks good, one thing I was thinking though is it might be better to have the `authorization_decoder` take in a flask config as an arg to make it a little more flexible and less tied to env vars. If a user wished to use env vars they can just set it in the flask config. This will also give us the ability to have different jwt hash types as well. 
```
app.config['JWT_SECRET_KEY'] = os.environ(...) 
app.config['JWT_HASH'] = os.environ(...)
...
elif type == "Bearer":
        """Bearer format, returns the identity"""
        decoded_jwt = jwt.decode(token, config["JWT_SECRET_KEY"], algorithms=config['JWT_HASH'])
        return str(decoded_jwt["identity"])
``` 
Thanks for looking into this and I look forward to seeing the PR. Feel free to name the JWT keys to whatever makes the most sense inline with the spec.

**Comment by msdcanderson** [comment]
Hi @jessecooper thanks for that feedback.

I have just popped the code into a forked repo here: https://github.com/msdcanderson/flask-authz/tree/bearer-token

I will have another go with your suggestions before I create a PR.

**Comment by msdcanderson** [comment]
Hi @jessecooper,

I had a look at putting in your suggested changes, but I'm struggling.

If we modify the function to include the jwt_hash and jwt_secret_key: 
```
def authorization_decoder(auth_str: str, jwt_secret_key, jwt_hash):
```
then this then impacts the basic type:
```
    if type == "Basic":
        """Basic format <user>:<password> return only the user"""
        return b64decode(token).decode().split(":")[0]
    elif type == "Bearer":
        """Bearer format, returns the identity"""
        # decoded_jwt = jwt.decode(
        #     token, os.environ["JWT_SECRET_KEY"], algorithms=["HS256"]
        # )
        decoded_jwt = jwt.decode(
            token, jwt_secret_key, algorithms=[jwt_hash]
        )
        return str(decoded_jwt["identity"])
    else:
        raise UnSupportedAuthType("%s Authorization is not supported" % type)
```

I'm not too sure how to read in the app.configs in this function.
Cheers

**Comment by dfresh613** [comment]
Lets consider adding the authorization_decoder property to the CasbinEnforcer class in a similar manner to how the adapter and watcher modules are added and used.

EX:
```
from utils import authorization_decoder

CasbinEnforcer(self, app, adapter, watcher=None, auth_decoder=authorization_decoder):
  self.auth_decoder = auth_decoder
```

And change line 58 CasbinEnforcer to use the class auth_decoder:
```
owner=self.auth_decoder(request.headers.get(header))  # this would be the Authorization Header
```

I believe this would allow more extensibility of determining how to decode the header, and where to get the secret/hash from (env, file, other db, docker secret, etc), algorithms to use, etc.

Defining the auth_decoder as a class property would also pave the way to updating the default auth_decoder with vars pulled from app.config in the __init__ method.

**Comment by hsluoyz** [comment]
Any update?

**Comment by hsluoyz** [comment]
@msdcanderson can you make a PR to add the `auth_decoder()` way?

**Comment by shenwpo** [comment]
添加config参数是否值得考虑
![image](https://user-images.githubusercontent.com/63697685/110229599-a86b3000-7f45-11eb-9caa-9f0d2be7dacd.png)
[https://github.com/pycasbin/flask-authz/compare/master...shenwpo:master](url)

**Comment by hsluoyz** [comment]
@shenwpo plz make a PR so we can review on it.

**Comment by hsluoyz** [comment]
@msdcanderson PR merged: https://github.com/pycasbin/flask-authz/pull/18

@Zxilly can you make a new release on both pypi and GitHub Releases?

**Comment by Zxilly** [comment]
@hsluoyz will do this later

**Comment by hsluoyz** [comment]
@Zxilly or establish the auto semantic-release system, which would be better :)

**Comment by Zxilly** [comment]
@will make a ci pull request later
