### ISSUE TITLE
The vast majority of casbin models can't be used in flask-authz

### ISSUE THREAD

**Issue by herve-brun** [pycasbin/flask-authz#13]
And this indirectly documented as the RESTful model is the only one which is.

In fact, the `CasbinEnforcer.enforcer` annotation is enforcing the access verification like this :
```python
...
78: if self.e.enforce(
79:     owner.strip('"'), str(request.url_rule), request.method
80: ):
...
```

**Comment by hsluoyz** [comment]
@jessecooper @dfresh613

**Comment by jessecooper** [comment]
@herve-brun Please provide examples and test cases.

**Comment by herve-brun** [comment]
A rant from a frustated developer and a silly github issue.
I am this developer, and I'm not proud of it.

Sorry for the inconvinience...

**Comment by jessecooper** [comment]
np, we have all been that developer at some point(s) in time. Thanks for following up and closing it out.
