### ISSUE TITLE
policy cannot support pattern *

### ISSUE THREAD

**Issue by zazayaya** [pycasbin/flask-authz#14]
Policy config：
-----------------------------------
p, *, /login, *

error message：
-----------------------------------
2020-11-03 11:32:11,148 - INFO - Request: test, /login, GET ---> False
127.0.0.1 - - [03/Nov/2020 11:32:11] "GET /login HTTP/1.1" 401 -

**Comment by zazayaya** [comment]
Policy config：

p, *, /login, *

**Comment by hsluoyz** [comment]
@zazayaya use `keyMatch()` in your model.

**Comment by zazayaya** [comment]
still 401，for this config，can you give me an example conf, hope you update the demo config

[matchers]
m = g(r.sub, p.sub) && (r.obj == p.obj || p.obj == "*" || keyMatch(r.obj, p.obj)) && (r.act == p.act || p.act == "*")

**Comment by zazayaya** [comment]
> @zazayaya use `keyMatch()` in your model.

still 401，for this config，can you give me an example conf, hope you update the demo config

[matchers]
m = g(r.sub, p.sub) && (r.obj == p.obj || p.obj == "" || keyMatch(r.obj, p.obj)) && (r.act == p.act || p.act == "")

**Comment by zazayaya** [comment]
> @zazayaya use `keyMatch()` in your model.

still 401，for this config，can you give me an example conf, hope you update the demo config

[matchers]
m = g(r.sub, p.sub) && (r.obj == p.obj || p.obj == "" || keyMatch(r.obj, p.obj)) && (r.act == p.act || p.act == "")

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/pycasbin/flask-authz/commit/be3596f34a3748592fbe1b512cf3557a1d5280a7
