### ISSUE TITLE
Failed to release on pypi

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/flask-authz#26]

**Comment by hsluoyz** [comment]
@Zxilly error: https://github.com/pycasbin/flask-authz/runs/2588929535?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/118347668-87dbd980-b577-11eb-9b61-b2488b9af544.png)

**Comment by hsluoyz** [comment]
@Zxilly v2.3.0 is not released in pypi: https://pypi.org/project/flask-authz/#history

**Comment by Zxilly** [comment]
@abichinger Could you please help to solve this?

**Comment by abichinger** [comment]
@Zxilly I'm on it. 👍

**Comment by hsluoyz** [comment]
@Zxilly v2.3.0 is still not released in pypi: https://pypi.org/project/flask-authz/#history

If this is expected, please release it manually.

**Comment by Zxilly** [comment]
@hsluoyz I will manually release it.

**Comment by Zxilly** [comment]
@hsluoyz released
