### ISSUE TITLE
Their should be  an API with one of the endpoint as casbin_sqlalchemy_adapter to provide role based access control in real time

### ISSUE THREAD

**Issue by princekrroshan01** [pycasbin/flask-authz#3]
their should be APIs like insert policy and delete policy  which interacts with casbin_sqlalchmey_adapter and changes policy rules in real time

**Comment by hsluoyz** [comment]
@techoner

**Comment by princekrroshan01** [comment]
Hi, @hsluoyz some time back I had made a pull request for this issue. but you closed the PR saying that you have used a file adapter as an example.

**Comment by hsluoyz** [comment]
You can use Management API: https://casbin.org/docs/en/management-api

**Comment by princekrroshan01** [comment]
Hi, @hsluoyz  I had made this pull request after consulting with @techoner.I had raised this issue when I was making a proposal for GSoC which is making a flask-extension for authorization. I thought maybe I could get some insight from it.

**Comment by hsluoyz** [comment]
@techoner
