### ISSUE TITLE
Support setting Owner Username for Audit logging when using owner_loader

### ISSUE THREAD

**Issue by daobeng** [pycasbin/flask-authz#33]
when using `owner_loader` instead of 'CABSIN_OWNER_HEADERS' (request headers in general), there seems to be no way to set the owner's username for audit logging. Can we provide support for setting an owner name when using `owner_loader` preferably outside of request headers?

**Comment by hsluoyz** [comment]
@jessecooper @dfresh613

**Comment by dfresh613** [comment]
Definitely seems like we should audit log the enforce attempts for owner_loader in the same way we do for headers.

Seems like a pretty straightforward re-factor: 

- extract calls of `self.e.enforce` from `casbin_enforcer.py` into a separate function `try_enforce` 
- `try_enforce` method can consistently log audit messages without duplicating log code

We encourage PRs for improvements like this. If this is a feature that will benefit your use case, maybe you can take a shot at it @daobeng

**Comment by hsluoyz** [comment]
@Abingcbc @fabian4 

/cc @leeqvip

**Comment by hsluoyz** [comment]
@Nekotoxin 

/cc @leeqvip

**Comment by Nekotoxin** [comment]
@daobeng 
Hello, you can try to set username as follow to resolve the problem.
![image](https://user-images.githubusercontent.com/75596353/188270850-68a329ff-a94b-4f3f-b06c-6dc9e5926b7a.png)

**Comment by hsluoyz** [comment]
Closed as resolved
