### ISSUE TITLE
Whitespace in group name not fully supported

### ISSUE THREAD

**Issue by dfresh613** [pycasbin/flask-authz#34]
**Background:**
flask-authz attempts to handle the groups header whether it is comma delimited, or space delimited. For example, both of these groups headers are supported, and will be converted into a list for checking against rbac rules:
- "group1 group2 group3". --> ["group1", "group2", "group3"]
- "group1, group2, group3" --> ["group1", "group2", "group3"]

This parsing and handling is done by sanitize_group_headers function: https://github.com/pycasbin/flask-authz/blob/master/flask_authz/casbin_enforcer.py#L152

**Problem**
This general parsing though comes with the drawback, of not fully supporting group names with spaces in them `"Some group"`. In most cases it will strip out the whitespace causing the name to not match what's actually in AD. If the user only belongs to one group, the parsing will split() that into 2 groups by the whitespace.

I've added some failing unit tests which depicts this problematic behavior: https://github.com/dfresh613/flask-authz/commit/8f6cbc3090a79204193efca518e999e1d231e9f2

I propose we add a configuration setting `delimiter` to specify the group header delimiter so that we can more intelligently parse the expected groups. Default value would be `,` as thats what i've seen mostly used. 

For the time being - if anyone experiences this the workaround is to just remove spaces when declaring your rbac roles:

`"group name" -> "groupname"`

**Comment by ffyuanda** [comment]
@dfresh613 Sure! Adding the config to determine the delimiter would be a good idea, though it seems to be a convention to not include whitespaces while naming your stuffs, in case that might lead to unexpected behavior like this one :)
