### ISSUE TITLE
Bump simpleeval - setuptools >=58 supported.

### ISSUE THREAD

**Issue by Tyskiep99** [pycasbin/flask-authz#40]
simpleeval==0.9.10 cannot build with setuptools >=58.

**Comment by Tyskiep99** [comment]
This lib (among others) from the requirement files are not even used, and shipped with Casbin or Flask already.
I believe the unsued deps can just be removed (werkzeug etc...)

**Comment by hsluoyz** [comment]
@Tyskiep99 I think you are right, see: https://github.com/pycasbin/flask-authz/blob/master/requirements.in and https://github.com/pycasbin/flask-authz/blob/master/requirements.txt

Can you make a PR?

**Comment by Tyskiep99** [comment]
I will try to: 
https://github.com/pycasbin/flask-authz/pull/42
it should cover this issue and flask2
