### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/flask-authz#43]
https://github.com/pycasbin/flask-authz/runs/4995545055?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/151690753-d4c39c88-0314-45d1-9c13-094cba351ee2.png)

**Comment by hsluoyz** [comment]
@Tyskiep99 @fabian4

**Comment by Tyskiep99** [comment]
I am not super familiar with bumpversion nor with this repo setup, but I think that this should be bumped too: https://github.com/pycasbin/flask-authz/blob/master/.bumpversion.cfg#L2
